default.extend-ignore-identifiers-re = [
    "ANDed",
    "arange",
    "iy1",
    "iy2",
    "EIS",
    "eis",
    "EIT",
    "eit",
    "HAE",
    "hsi",
    "Hsi",
    "nd",
    "NDData",
    "alog",
    "alog10",
    "FOVs",
    "FOV",
    "Emiss",
    "emiss",
    "noy",
    "sav",
    "_slac",
    "bck",
]
