name: main
on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy-exercise:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install tox

      - name: Run tox
        run: |
          tox -e codestyle

  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        pip install -e .
        pip install pytest
        pip install tox

    - name: Run tox
      run: |
        tox -e py312

    - name: Run pytest ex2
      run: |
        pytest -vvv ./nm_lib/nm_ex/test/test_ex_2b.py
